# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        ('secret', '0002_remove_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_like',
        ),
        migrations.AddField(
            model_name='secret',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='log.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
